name: Blue-bike

on:
  push:
     branches:
       - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  Blue-bike:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Fetch and write data Blue-bike
        uses: lucasderveaux/LDES_Republisher@main
        with:
          url: "https://www.pieter.pm/Blue-Bike-to-Linked-GBFS/root.ttl"
          storage: BB
          literal_values: '["https://w3id.org/gbfs#bikes_available"]'
          uri_timestamp: 'http://purl.org/dc/terms/created'
          uri_feature_of_interest: 'http://purl.org/dc/terms/isVersionOf'
